version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../morphological-api:/var/www/morphological-api
    depends_on:
      - php
    cpus: 1
    mem_limit: 1g

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
    volumes:
      - mysql_data:/var/lib/mysql
    cpus: 2
    mem_limit: 2g

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php
    volumes:
      - ../morphological-api:/var/www/morphological-api
    depends_on:
      - mysql
    cpus: 4
    mem_limit: 2g

  jumanpp:
    build:
      context: .
      dockerfile: Dockerfile-jumanpp
    container_name: jumanpp
    volumes:
      - ../morphological-api:/var/www/morphological-api
    depends_on:
      - php
    cpus: 1
    mem_limit: 1g

  node:
    image: node:16-alpine
    container_name: node
    working_dir: /var/www/morphological-api
    volumes:
      - ../morphological-api:/var/www/morphological-api
    command: sh -c "npm install && npm run dev"
    cpus: 2
    mem_limit: 2g

volumes:
  mysql_data:
